services:
  - type: web
    name: qubit
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TWELVE_DATA_API_KEY
        sync: false